<?php ($can = !empty($p['can_talk']) || !empty($p['is_friend'])); ?>

<div class="bg-surface-2 rounded-2xl border border-border p-4 flex flex-wrap items-center gap-3">
    <a href="<?php echo e(url('/people/' . $p['id'])); ?>" class="flex items-center gap-3 min-w-0 flex-1 group">
        <div class="w-12 h-12 rounded-full bg-brand/10 text-brand flex items-center justify-center font-semibold flex-shrink-0 overflow-hidden relative">
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($p['avatar_url']): ?><img src="<?php echo e($p['avatar_url']); ?>" alt="" class="w-full h-full object-cover"><?php else: ?><?php echo e(strtoupper(mb_substr($p['name'], 0, 1))); ?><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        </div>
        <div class="min-w-0">
            <div class="flex flex-wrap items-center gap-2">
                <span class="font-medium text-ink truncate group-hover:underline"><?php echo e($p['name']); ?></span>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($p['is_friend'])): ?><span class="text-[10px] rounded-full bg-green-100 text-green-800 px-2 py-0.5"><?php echo e(__('Friend')); ?></span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($p['is_former'])): ?><span class="text-[10px] rounded-full bg-gray-200 text-gray-700 px-2 py-0.5"><?php echo e(__('Unfriended')); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($p['ended'])): ?> · <?php echo e($p['ended']); ?><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($p['is_team'])): ?><span class="text-[10px] rounded-full bg-blue-100 text-blue-800 px-2 py-0.5"><?php echo e(__('Team')); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($p['role'])): ?> · <?php echo e($p['role']); ?><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($p['online'])): ?><span class="w-2 h-2 rounded-full bg-green-500" title="<?php echo e(__('Online')); ?>"></span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
            </div>
            <div class="text-xs text-muted truncate"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($p['username'])): ?>&#64;<?php echo e($p['username']); ?> · <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><?php echo e($p['email'] ?? ''); ?></div>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($p['call_status'])): ?><div class="text-xs text-green-600"><?php echo e($p['call_status'] === 'ringing' ? __('Ringing…') : __('Call in progress')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($p['preview'])): ?><div class="text-sm text-ink truncate"><?php echo e($p['preview']); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($p['status_label'])): ?><div class="text-xs <?php echo e(!empty($p['online']) ? 'text-green-600 font-medium' : 'text-muted'); ?> truncate"><?php echo e($p['status_label']); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        </div>
    </a>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(\App\Support\FriendSettings::chatEnabled() && !empty($p['is_former'])): ?>
        <a href="<?php echo e(url('/friends/chat/' . $p['id'])); ?>" class="btn-secondary"><?php echo e(__('Chat history')); ?></a>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(\App\Support\FriendSettings::chatEnabled() && $can && empty($p['is_former'])): ?>
        <a href="<?php echo e(url('/friends/chat/' . $p['id'])); ?>" class="btn-primary"><?php echo e(__('Chat')); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(($p['unread'] ?? 0) > 0): ?><span class="ml-1 text-xs rounded-full bg-white/25 px-1.5 py-0.5"><?php echo e($p['unread']); ?></span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></a>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(\App\Support\FriendSettings::callsEnabled() && $can && empty($p['is_former'])): ?>
        <button type="button" onclick="window.FriendCall && window.FriendCall.start(<?php echo e($p['id']); ?>, <?php echo \Illuminate\Support\Js::from($p['name'])->toHtml() ?>)" class="btn-secondary"><?php echo e(__('Call')); ?></button>
        <button type="button" onclick="window.FriendCall && window.FriendCall.startVideo(<?php echo e($p['id']); ?>, <?php echo \Illuminate\Support\Js::from($p['name'])->toHtml() ?>)" class="btn-secondary"><?php echo e(__('Video')); ?></button>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <a href="mailto:<?php echo e($p['email'] ?? ''); ?>" class="btn-secondary"><?php echo e(__('Email')); ?></a>
    <a href="<?php echo e(url('/people/' . $p['id'])); ?>" class="text-xs text-muted hover:text-ink"><?php echo e(__('Profile')); ?></a>
</div>
<?php /**PATH /home/dahimail.com/public_html/resources/views/livewire/friends/person-row.blade.php ENDPATH**/ ?>