        <?php
            $groups = [[__('Upcoming'), $lists['upcoming'], true], [__('Recent'), $lists['recent'], false]];
        ?>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $groups; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$label, $items, $active]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoop($loop->index); ?><?php endif; ?>
            <div class="space-y-3">
                <h2 class="text-base font-semibold text-ink"><?php echo e($label); ?></h2>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $m): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoop($loop->index); ?><?php endif; ?>
                    <div class="bg-surface-2 rounded-2xl border border-border p-4 flex flex-wrap items-center gap-3">
                        <div class="min-w-0 flex-1">
                            <div class="flex items-center gap-2"><span class="font-medium text-ink truncate"><?php echo e($m['title']); ?></span><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($m['status'] === 'live'): ?><span class="text-[10px] rounded-full bg-red-100 text-red-700 px-2 py-0.5"><?php echo e(__('Live')); ?> · <?php echo e($m['participants']); ?></span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
                            <div class="text-xs text-brand font-medium" data-start="<?php echo e($m['scheduled_at'] ?? ''); ?>" data-live="<?php echo e($m['status'] === 'live' ? 1 : 0); ?>"></div>
                            <div class="text-xs text-muted"><?php echo e($m['when'] ?: __('Instant meeting')); ?> · <?php echo e($m['is_host'] ? __('You are the host') : __('Host: :n', ['n' => $m['host']])); ?> · <?php echo e($m['pretty']); ?></div>
                        </div>
                        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($active): ?>
                            <a href="<?php echo e(url('/meet/' . $m['code'])); ?>" class="btn-primary"><?php echo e($m['status'] === 'live' ? __('Join') : __('Open')); ?></a>
                            <button type="button" class="btn-secondary" onclick="navigator.clipboard.writeText(<?php echo \Illuminate\Support\Js::from($m['url'])->toHtml() ?>).then(function(){alert('<?php echo e(__('Link copied')); ?>');})"><?php echo e(__('Copy link')); ?></button>
                            <button type="button" class="btn-secondary" onclick="shareMeeting(<?php echo \Illuminate\Support\Js::from($m['title'])->toHtml() ?>, <?php echo \Illuminate\Support\Js::from($m['url'])->toHtml() ?>, <?php echo \Illuminate\Support\Js::from($m['pretty'])->toHtml() ?>, <?php echo \Illuminate\Support\Js::from($m['when'])->toHtml() ?>)"><?php echo e(__('Share')); ?></button>
                            <a class="btn-secondary" href="<?php echo e(url('/meet/' . $m['code'] . '/ics')); ?>" title="<?php echo e(__('Add to Google, Outlook or Apple calendar')); ?>"><?php echo e(__('Add to calendar')); ?></a>
                            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($m['is_host']): ?>
                                <details class="w-full">
                                    <summary class="text-sm text-brand cursor-pointer"><?php echo e(__('Change title, time or length (reschedule)')); ?></summary>
                                    <form method="POST" action="<?php echo e(url('/meetings/' . $m['code'] . '/update')); ?>" class="mt-3 grid sm:grid-cols-4 gap-3 items-end">
                                        <?php echo csrf_field(); ?>
                                        <label class="block sm:col-span-4"><span class="text-xs text-muted"><?php echo e(__('Title')); ?></span><input name="title" class="input" value="<?php echo e($m['title']); ?>" maxlength="150"></label>
                                        <label class="block"><span class="text-xs text-muted"><?php echo e(__('New date')); ?></span><input type="date" name="date" class="input" value="<?php echo e($m['scheduled_at'] ? \Illuminate\Support\Carbon::parse($m['scheduled_at'])->setTimezone(auth()->user()->timezone ?: config('app.timezone'))->format('Y-m-d') : ''); ?>"></label>
                                        <label class="block"><span class="text-xs text-muted"><?php echo e(__('New time')); ?></span><input type="time" name="time" class="input" value="<?php echo e($m['scheduled_at'] ? \Illuminate\Support\Carbon::parse($m['scheduled_at'])->setTimezone(auth()->user()->timezone ?: config('app.timezone'))->format('H:i') : ''); ?>"></label>
                                        <label class="block"><span class="text-xs text-muted"><?php echo e(__('Length (min)')); ?></span><input type="number" name="duration" min="15" max="480" step="15" class="input" value="<?php echo e($m['duration']); ?>"></label>
                                        <button class="btn-primary" type="submit"><?php echo e(__('Save changes')); ?></button>
                                    </form>
                                    <p class="text-xs text-muted mt-1"><?php echo e(__('People you invited get a notification about the change.')); ?></p>
                                </details>
                            <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($m['is_host'] && $m['status'] !== 'live'): ?>
                                <form method="POST" action="<?php echo e(url('/meetings/' . $m['code'] . '/cancel')); ?>" onsubmit="return confirm(<?php echo \Illuminate\Support\Js::from(__('Cancel this meeting?'))->toHtml() ?>)"><?php echo csrf_field(); ?><button type="submit" class="text-sm text-red-600"><?php echo e(__('Cancel')); ?></button></form>
                            <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                    </div>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
                    <div class="text-sm text-muted py-4"><?php echo e($active ? __('No upcoming meetings. Start one above.') : __('Nothing yet.')); ?></div>
                <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
            </div>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
<?php /**PATH /home/dahimail.com/public_html/resources/views/meetings/_list.blade.php ENDPATH**/ ?>